apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: us.gcr.io/time-382620/time-enter_data
          ports:
            - containerPort: 3306
              name: mysql-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
