apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-data
  template:
    metadata:
      labels:
        app: view-data
    spec:
      containers:
      - name: view-data
        image: us.gcr.io/time-382620/time-view_data
        ports:
        - containerPort: 8004
        env:
        - name: AUTH_SERVICE_HOST
          value: "nodelogin"
