apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: analytics-service
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nodelogin
  labels:
    app: nodelogin
spec:
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: nodelogin
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: enter-data
  labels:
    app: enter-data
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 5000
  selector:
    app: enter-data
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: view-data
  labels:
    app: view-data
spec:
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  selector:
    app: view-data
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  ports:
    - name: mysql-db
      port: 3306
      targetPort: 3306
  selector:
    app: mysql-db
  type: LoadBalancer